name: 🐛 Bug Report
description: Report a bug or issue with PYDNS Scanner
title: "[Bug]: "
labels: ["bug"]
assignees:
  - xullexer
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! Please provide as much detail as possible.

  - type: input
    id: python-version
    attributes:
      label: Python Version
      description: What version of Python are you using?
      placeholder: "e.g., 3.11.4"
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      description: What operating system are you using?
      options:
        - Windows 10
        - Windows 11
        - Ubuntu
        - Debian
        - CentOS
        - Fedora
        - Arch Linux
        - macOS (Intel)
        - macOS (Apple Silicon)
        - Other Linux
        - Other
    validations:
      required: true

  - type: input
    id: os-version
    attributes:
      label: OS Version
      description: What is your OS version?
      placeholder: "e.g., Windows 11 23H2, Ubuntu 22.04, macOS 14.2"
    validations:
      required: true

  - type: input
    id: device
    attributes:
      label: Device / Hardware
      description: What device or hardware are you running on?
      placeholder: "e.g., Dell XPS 15, MacBook Pro M2, VPS, Raspberry Pi 4"
    validations:
      required: false

  - type: input
    id: isp
    attributes:
      label: Internet Provider / ISP
      description: Who is your internet service provider? (helpful for network-related issues)
      placeholder: "e.g., Comcast, AT&T, Irancell, MCI"
    validations:
      required: false

  - type: dropdown
    id: slipstream-enabled
    attributes:
      label: Slipstream Testing
      description: Were you using Slipstream proxy testing?
      options:
        - "Yes"
        - "No"
    validations:
      required: true

  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Describe the bug clearly. What did you expect to happen?
      placeholder: "Describe the issue..."
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: How can we reproduce this issue?
      placeholder: |
        1. Run the scanner with...
        2. Select option...
        3. See error...
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Error Logs / Screenshots
      description: Paste any error messages or attach screenshots
      placeholder: "Paste logs here or drag and drop screenshots..."
    validations:
      required: false

  - type: input
    id: cidr-file
    attributes:
      label: CIDR File Used
      description: What CIDR file were you scanning? (optional)
      placeholder: "e.g., iran-ipv4.cidrs, custom file with X entries"
    validations:
      required: false

  - type: input
    id: concurrency
    attributes:
      label: Concurrency Setting
      description: What concurrency level were you using?
      placeholder: "e.g., 100, 500"
    validations:
      required: false
