name: ❓ Question / Help
description: Ask a question or get help with usage
title: "[Question]: "
labels: ["question"]
assignees:
  - xullexer
body:
  - type: markdown
    attributes:
      value: |
        Need help? Ask your question here!

  - type: textarea
    id: question
    attributes:
      label: Your Question
      description: What would you like to know?
      placeholder: "How do I...?"
    validations:
      required: true

  - type: input
    id: python-version
    attributes:
      label: Python Version
      description: What version of Python are you using?
      placeholder: "e.g., 3.11.4"
    validations:
      required: false

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      description: What operating system are you using?
      options:
        - Windows
        - Linux
        - macOS
    validations:
      required: false

  - type: textarea
    id: tried
    attributes:
      label: What have you tried?
      description: What solutions or documentation have you already checked?
      placeholder: "I've tried..."
    validations:
      required: false
